spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.10.228:3306/redis_boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  redis:
    port: 6379
    host: 10.10.10.228
    database: 0
    password:
    timeout: 6000ms
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: cn.com.yangzhenyu.*.entity
  global-config:
    db-config:
      id-type: auto